global:
  wwwDomain: abpzerotemplate-www
  wwwUrl: "https://abpzerotemplate-www"
  nginxProxyBufferSize: "32k"
  nginxProxyBuffersNumber: "8"
  defaultConnString: "Server=${DB_SERVER};Database=${DB_NAME};User ID=${DB_USER};Password=${DB_PASSWORD}"
www:
  containerImage: "abpzerotemplate-mvc"
dbmigrator:
  containerImage: "abpzerotemplate-migrator"