version: '3.7'

services:      

  mycompanyname.abpzerotemplate.web.host:
    image: ${DOCKER_REGISTRY-}mycompanynameabpzerotemplatewebhost
    container_name: mycompanynameabpzerotemplatewebhost_container
    build:
      context: ../../
      dockerfile: src/DownloadDevTools.Web.Host/Dockerfile
    environment:
      - ConnectionStrings__Default=Server=${DB_SERVER};Database=${DB_NAME};User=${DB_USER};Password=${DB_PASSWORD};
      - Abp__RedisCache__ConnectionString=localhost:6379
    ports:
      - "44301:443"
    networks:
      - mycompanyname.abpzerotemplate

networks:
  mycompanyname.abpzerotemplate:
    external:
      name: mycompanyname.abpzerotemplate