version: '3.7'

services:
  
  mycompanyname.abpzerotemplate.web.public:
    image: ${DOCKER_REGISTRY-}mycompanynameabpzerotemplatewebpublic
    container_name: mycompanynameabpzerotemplatewebpublic_container
    build:
      context: ../../
      dockerfile: src/DownloadDevTools.Web.Public/Dockerfile
    environment:
      - ConnectionStrings__Default=Server=${DB_SERVER};Database=${DB_NAME};User=${DB_USER};Password=${DB_PASSWORD};
    ports:
      - "44303:443"
    networks:
      - mycompanyname.abpzerotemplate

networks:
  mycompanyname.abpzerotemplate:
    external:
      name: mycompanyname.abpzerotemplate