version: '3.7'

services:

  mssqlDb:
    container_name: mssqlDb_container
    image: microsoft.repo.stinascloud.ir/mssql/server
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: ${DB_SA_PASSWORD}
      ACCEPT_EULA: Y
    volumes:
      - mssqlDb-data:/var/opt/mssql
    networks:
      - mycompanyname.abpzerotemplate

  redis:
    image: redis:alpine
    container_name: redis_container
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - mycompanyname.abpzerotemplate

volumes:
  mssqlDb-data:
   name: "mssqlDb-data"

networks:
  mycompanyname.abpzerotemplate:
    external:
      name: mycompanyname.abpzerotemplate