version: '3.7'

services:

  mycompanyname.abpzerotemplate.migrator:
    image: ${DOCKER_REGISTRY-}mycompanynameabpzerotemplatemigrator
    container_name: mycompanynameabpzerotemplatemigrator_container
    build:
      context: ../../
      dockerfile: src/DownloadDevTools.Migrator/Dockerfile
    environment:
      - ASPNETCORE_Docker_Enabled=true
      - ConnectionStrings__Default=Server=${DB_SERVER};Database=${DB_NAME};User=${DB_USER};Password=${DB_PASSWORD};
    networks:
      - mycompanyname.abpzerotemplate
      
networks:
  mycompanyname.abpzerotemplate:
    external:
      name: mycompanyname.abpzerotemplate